name: ripplenet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - ipympl
  - matplotlib
  - pandas
  - seaborn
  - jupyter
  - pip
  - pip:
    - tensorflow
    # - h5py
    # - numpy
